# -*- coding: utf-8 -*-
from django.core.management.base import BaseCommand
import requests
import telebot
from bot.models import Subscriber

class Command(BaseCommand):
    help = 'Test'

    def handle(self, *args, **options):
        bot_id = '1308591822:AAFghKn_dOJaME7P82ohf6TjfHOLP72Xo_A'
        self.bot_starter(bot_id)

                #bot.send_message(chat_id, "This message was generated by Telebot")
    def start_bot(self, bot_id):
        print('Start bot')
        bot = telebot.TeleBot(bot_id)
        @bot.message_handler(commands=['start', 'help'])
        def send_welcome(message):
            subscriber = Subscriber.objects.filter(telegram_id=int(message.chat.id))
            if len(subscriber) > 0:
                bot.send_message(message.chat.id, "Welcome back"+message.from_user.first_name)
            else:
                Subscriber.objects.create(
                    first_name = message.from_user.first_name,
                    last_name=message.from_user.last_name,
                    username=message.from_user.username,
                    telegram_id=message.chat.id
                )
                bot.send_message(message.chat.id, "Hello" + message.from_user.first_name)
        bot.polling(timeout=1)

    def bot_starter(self, bot_id):
        try:
            self.start_bot(bot_id)
        except BaseException as e:
            print(e)
            self.bot_starter(bot_id)

#
# Telegram-API-key:  1308591822:AAFghKn_dOJaME7P82ohf6TjfHOLP72Xo_A
# https://api.telegram.org/bot1308591822:AAFghKn_dOJaME7P82ohf6TjfHOLP72Xo_A/getUpdates
# chat ID: 1563243177

# chat_id = '1563243177'
        # message = 'Hi guys!'
        # url = 'https://api.telegram.org/bot'+bot_id+'/sendMessage?chat_id='+chat_id+'&text='+message
        # requests.get(url)
        # print('message was sent')