# Generated by Django 3.1.5 on 2021-01-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='message_text',
        ),
    ]
